Controllers/MembersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using W1.Data;
using W1.Models;

namespace W1.Controllers
{
    [Authorize]
    public class MembersController : Controller
    {
        private readonly PlacidDBContext _context;
        private readonly ApplicationDbContext _appcontext;
        private readonly IScopedService _scopedService;


        private readonly IWebHostEnvironment _appEnvironment;

        public MembersController(ApplicationDbContext appcontext, PlacidDBContext context, IWebHostEnvironment appEnvironment, IScopedService scopedService)
        {
            _context = context;
            _appEnvironment = appEnvironment;
            _scopedService = scopedService;
            _appcontext = appcontext;
        }

        [HttpPost]
        public async Task<IActionResult> VerifyUser(string email, string Code)
        {

            //_transientService.SetPlacidUser(email);
            //_transientService.SetPlacid(true);
            //PlacidSingleton.Instance.SetPlacid(false);

            //PlacidSingleton.Instance.SetPlacidUser(email);

             
            if (String.Compare("placiduser@xyztt.com", email) == 0 && String.Compare("23456", Code) == 0)
            {
                _scopedService.SetPlacidUser(email);
                _scopedService.SetPlacid(true);
                return RedirectToAction(nameof(Index));
            }
            else
            {
                PlacidSingleton.Instance.SetPlacid(false);
                PlacidSingleton.Instance.SetPlacidUser("");
                return RedirectToAction(nameof(Index), "home");
            }

            /*
            if (String.Compare(PlacidSingleton.Instance.GetPlacidUser().ToLower(), "placiduser@xyztt.com") == 0)
            {
                PlacidSingleton.Instance.SetPlacid(true);
                PlacidSingleton.Instance.SetPlacidUser(email);
                return RedirectToAction(nameof(Index));
            }
            else
            {
                PlacidSingleton.Instance.SetPlacid(false);
                PlacidSingleton.Instance.SetPlacidUser("");
                return RedirectToAction(nameof(Index), "home");
            }   
            */
            return RedirectToAction(nameof(Index), "home");
        }

 
        /// <summary>
        /// //////////////////////////////////////////////////////////////////////////////////////////////
        /// </summary>

        [HttpPost]
        public async Task<ActionResult> FileUpload1(IFormFile file, string LotNo, string Price, string AgentLastName, string AgentFirstName, string Email,

            //public async Task<ActionResult> FileUpload1(IFormFile file, int LotNo, string Price, string AgentLastName, string AgentFirstName, string Email,
            string OfficePhone, string CellPhone, string AgentUrl)
        {

            string finalLot = null;

             
            if (String.Compare(_scopedService.GetPlacidUser().ToLower(), "placiduser@xyztt.com") != 0)
            {
                return RedirectToAction(nameof(Index), "home");
            } 


            String OfficePhone1 = OfficePhone.Insert(3, "-");
            string OfficeFinal = OfficePhone1.Insert(7, "-");

            String CellPhone1 = CellPhone.Insert(3, "-");
            string CellPhoneFinal = CellPhone1.Insert(7, "-");


            string currency = "$" + " " + Price + ".00";

            if (ModelState.IsValid)
            {
                string finalLot1 = null;

                /*
                if (LotNo > 0 || LotNo <= 9)
                {
                    finalLot1 = "0" + LotNo.ToString();
                }
                else
                {
                    finalLot1 = LotNo.ToString();
                }  */
                await UploadFile(file, LotNo);
                Member member0 = new Member();
                member0.LotNo = LotNo;
                member0.Price = currency;
                member0.AgentLastName = AgentLastName;
                member0.AgentFirstName = AgentFirstName;
                member0.Email = Email;
                member0.OfficePhone = OfficeFinal;
                member0.CellPhone = CellPhoneFinal;
                member0.ImageName = file.FileName;
                member0.AgentUrl = AgentUrl;

                _context.Add(member0);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            else
            {
                Member member1 = new Member();
                member1.LotNo = LotNo;
                member1.Price = Price;
                member1.AgentLastName = AgentLastName;
                member1.AgentFirstName = AgentFirstName;
                member1.Email = Email;
                member1.OfficePhone = OfficePhone;
                member1.CellPhone = CellPhone;
                member1.ImageName = file.FileName;
                return View(member1);
            }
 
        }

        public async Task<bool> UploadFile(IFormFile file, string lotNo)
        {
            string path = "";
            bool iscopied = false;

 

            try
            {
                if (file.Length > 0)
                {
                    // var fnext = Path.GetExtension(file.FileName);
                    // string fname = LotNo + "." + fnext;
                    //  verify the 
                    string filename = lotNo + Path.GetExtension(file.FileName);
                    path = _appEnvironment.WebRootPath;
                    // Path.GetFullPath(Path.Combine(Directory.GetCurrentDirectory(), "Upload"));
                    var tt = path + "\\" + filename;
                    using (var filestream = new FileStream(path + "\\" + filename, FileMode.Create))  //        //Path.Combine(path, filename), FileMode.Create))
                    {
                        await file.CopyToAsync(filestream);
                    }
                    iscopied = true;
                }
                else
                {
                    iscopied = false;
                }
            }
            catch (Exception)
            {
                throw;
            }
            return iscopied;
        }


        /// <summary>
        /// /////////////////////////////////////////////////////////////////////////////////////////////////////
        /// </summary>
        







        // GET: Members
        public async Task<IActionResult> Index()
        {
          //  if (String.Compare(_scopedService.GetPlacidUser().ToLower(), "placiduser@xyztt.com") != 0)
          //  {
          //      return RedirectToAction(nameof(Index), "home");
          //  }



            return View(await _context.Members.ToListAsync());
        }

        // GET: Members/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            /*
           if (String.Compare(PlacidSingleton.Instance.GetPlacidUser().ToLower(), "placiduser@xyztt.com") != 0)
           {
               return RedirectToAction(nameof(Index), "home");
           }*/


            if (id == null)
            {
                return NotFound();
            }

            var member = await _context.Members
                .FirstOrDefaultAsync(m => m.ID == id);
            if (member == null)
            {
                return NotFound();
            }
            //PlacidSingleton.Instance.SetPlacid(false);
            return View(member);
        }

        // GET: Members/Create
        public IActionResult Create()
        {
            /*
            if (String.Compare(PlacidSingleton.Instance.GetPlacidUser().ToLower(), "placiduser@xyztt.com") != 0)
            {
                return RedirectToAction(nameof(Index), "home");
            }*/
            return View();
        }

        // POST: Members/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,LotNo,Price,AgentLastName,AgentFirstName,Email,OfficePhone,CellPhone,AgentUrl,ImageName")] Member member)
        {
            /*
            if (String.Compare(PlacidSingleton.Instance.GetPlacidUser().ToLower(), "placiduser@xyztt.com") != 0)
            {
                return RedirectToAction(nameof(Index), "home");
            }*/

            if (ModelState.IsValid)
            {
                _context.Add(member);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(member);
        }

        // GET: Members/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            /*
           if (String.Compare(PlacidSingleton.Instance.GetPlacidUser().ToLower(), "placiduser@xyztt.com") != 0)
           {
               return RedirectToAction(nameof(Index), "home");
           }*/

            if (id == null)
            {
                return NotFound();
            }

            var member = await _context.Members.FindAsync(id);
            if (member == null)
            {
                return NotFound();
            }
           // PlacidSingleton.Instance.SetPlacid(false);
            return View(member);
        }

        // POST: Members/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,LotNo,Price,AgentLastName,AgentFirstName,Email,OfficePhone,CellPhone,AgentUrl,ImageName")] Member member)

Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using W1.Data;
using W1.Models;

namespace W1.Controllers
{
    [Authorize]
    public class UsersController : Controller
    {
        private readonly PlacidDBContext _context;

        public UsersController(PlacidDBContext context)
        {
            _context = context;
        }

        // GET: Users
        public async Task<IActionResult> Index()
        {
            /*
            if (String.Compare(PlacidSingleton.Instance.GetPlacidUser().ToLower(), "placiduser@xyztt.com") != 0)
            {
                return RedirectToAction(nameof(Index), "home");
            }
            */
            return View(await _context.Users.ToListAsync());
        }

        // GET: Users/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            /*
         if (String.Compare(PlacidSingleton.Instance.GetPlacidUser().ToLower(), "placiduser@xyztt.com") != 0)
         {
             return RedirectToAction(nameof(Index), "home");
         }
         */

            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.Users
                .FirstOrDefaultAsync(m => m.Id == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // GET: Users/Create
        public IActionResult Create()
        {
            /*
         if (String.Compare(PlacidSingleton.Instance.GetPlacidUser().ToLower(), "placiduser@xyztt.com") != 0)
         {
             return RedirectToAction(nameof(Index), "home");
         }
         */

            return View();
        }

        // POST: Users/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,FirstName,LastName,FullName,LotNo,Cell")] User user)
        {
            /*
         if (String.Compare(PlacidSingleton.Instance.GetPlacidUser().ToLower(), "placiduser@xyztt.com") != 0)
         {
             return RedirectToAction(nameof(Index), "home");
         }
         */

            if (ModelState.IsValid)
            {
                _context.Add(user);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(user);
        }

        // GET: Users/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            /*
        if (String.Compare(PlacidSingleton.Instance.GetPlacidUser().ToLower(), "placiduser@xyztt.com") != 0)
        {
            return RedirectToAction(nameof(Index), "home");
        }
        */

            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.Users.FindAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            return View(user);
        }

        // POST: Users/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,FirstName,LastName,FullName,LotNo,Cell")] User user)
        {
            /*
        if (String.Compare(PlacidSingleton.Instance.GetPlacidUser().ToLower(), "placiduser@xyztt.com") != 0)
        {
            return RedirectToAction(nameof(Index), "home");
        }
        */


            if (id != user.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(user);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UserExists(user.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(user);
        }

        // GET: Users/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            /*
         if (String.Compare(PlacidSingleton.Instance.GetPlacidUser().ToLower(), "placiduser@xyztt.com") != 0)
         {
             return RedirectToAction(nameof(Index), "home");
         }
         */


            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.Users
                .FirstOrDefaultAsync(m => m.Id == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            /*
         if (String.Compare(PlacidSingleton.Instance.GetPlacidUser().ToLower(), "placiduser@xyztt.com") != 0)
         {
             return RedirectToAction(nameof(Index), "home");
         }
         */


            var user = await _context.Users.FindAsync(id);
            if (user != null)
            {
                _context.Users.Remove(user);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UserExists(int id)
        {
            return _context.Users.Any(e => e.Id == id);
        }
    }
}

Views/Members/Create.cshtml
@model W1.Models.Member

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Create Sale</h4>
<hr />
<div class="row">
    <div class="col-2">
         
    </div>
    <div class="col-md-8">
        <!--
        <form asp-action="Create">  -->
        <form method="post" enctype="multipart/form-data" asp-controller="Members" asp-action="FileUpload1">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="LotNo" class="control-label"></label>
                <input asp-for="LotNo" data-toggle="tooltip" data-html="true" title="alues 1 - 99 and A1 are valid" class="form-control" />
                <span asp-validation-for="LotNo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" data-toggle="tooltip" data-html="true" title="Enter unformatted number - example: 123456" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AgentLastName" class="control-label"></label>
                <input asp-for="AgentLastName" class="form-control" />
                <span asp-validation-for="AgentLastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AgentFirstName" class="control-label"></label>
                <input asp-for="AgentFirstName" class="form-control" />
                <span asp-validation-for="AgentFirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OfficePhone" class="control-label"></label>
                <input asp-for="OfficePhone" data-toggle="tooltip" data-html="true" title="Enter number no hyphens" class="form-control" />
                <span asp-validation-for="OfficePhone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CellPhone" class="control-label"></label>
                <input asp-for="CellPhone" data-toggle="tooltip" data-html="true" title="Enter number no hyphens"  class="form-control" />
                <span asp-validation-for="CellPhone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AgentUrl" class="control-label"></label>
                <input asp-for="AgentUrl" onfocusout="myFunction()" data-toggle="tooltip" data-html="true" title="Enter Agent Home listing" class="form-control" />
                <span asp-validation-for="AgentUrl" class="text-danger"></span>
            </div>
            <br />
            <br />
            <div class="form-group" align="center">
                <input id="fileclick" value="" data-toggle="tooltip" data-html="true" title="Choose Image file"  class="btn btn-primary" type="file" name="file" />
            </div>
            
            <div style="visibility: hidden" class="form-group">
                <label asp-for="ImageName" class="control-label"></label>
                <input id="ImageName1" data-toggle="tooltip" data-html="true" title="Imagve name from file chosen" asp-for="ImageName" value="" class="form-control" />
                <span asp-validation-for="ImageName" class="text-danger"></span>
            </div>
            <div align="center" class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
    <div class="col-2">
         
    </div>
</div>

<div align="center">
    <a asp-action="Index">Back to List</a>
</div>

 

@section Scripts
{
    <script>
                          
        $( document ).ready(function() {
        });

        /*
        function LotNoVerify(function(e)  ({
            var x = document.getElementById("LotNo");
            if ( x.value > 0 && x.value < 100 )
                  return;
            else
                  alert('Lot Number must be between 1 and 99')
                  e.preventDefault();
        )};  */


        function myFunction() {
            alert('Agent URL');
            var x = document.getElementById("AgentUrl");
            x.value = x.value.toUpperCase();
        }

        function DoAlertClick() {
            alert('clicked');
             
        }

        function DoAlert() {
            Swal.fire({
            title: "Good job!",
            text: "You clicked the button!",
            icon: "success"
            });
        }

        lightbox.option({
            'resizeDuration': 200,
            'wrapAround': true,
            'maxwidth': 388,
            'maxheight': 339
        });




        function jsonDialog12(jsonobj, modes, titleDialog, okcallback, cancelcallback, errorcallback) {
            // if (jsonobj === undefined || jsonobj === null) {
            //     if (errorcallback !== undefined)
            //         errorcallback("JSON Object is not valid");
            //     return false;
            // }

            var jsoncontent = document.createElement('div');
            jsoncontent.id = 'divjson';
            jsoncontent.style.display = "visible";

            $('#divjson').css('z-index', '100000');
            document.body.appendChild(jsoncontent);

            var jsoneditor = document.createElement('div');
            jsoneditor.style.width = '320px';
            jsoneditor.style.height = '280px';

            jsoncontent.appendChild(jsoneditor);

            if (modes === undefined || modes === null)
                modes = { mode: 'tree', modes: ['form', 'text', 'tree', 'view'] };


            // let img = document.createElement('img');
            // debugger;
            // img.src = 'https://media.geeksforgeeks.org/wp-content/uploads/20190529122828/bs21.png';


                //  debugger;
                    jsoneditor.append('<img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRLqBq0ilAid0OE2A0Qx94ujF_M9DugbAGVyg&usqp=CAU"  width = "320" height = "280"/>');
            //  debugger;


            //var editor = new JSONEditor(jsoneditor, modes);
            // editor.set(jsonobj);

            var destroy = function () {
                //editor.destroy();
                //jsoneditor.remove();
                $(jsoncontent).dialog('close');
                jsoncontent.remove();
                $('.ui-dialog').remove();
            };
            //https://api.jqueryui.com/position/
            //https://jqueryui.com/position/
            $(jsoncontent).dialog({
                height: 320, //560,
                width: 280,
                resizable: true,
                modal: true,
                //visibility: inherit,
                // dialogClass: "alert101",
                draggable: true,
                closeOnEscape: false,

                title: "Resource: " + titleDialog,
                position: {
                    my: "center",
                    at: "top",
                    of: window
                },
                buttons: [{
                    text: "OK",
                    style: "margin-right:40px; color:#3883fa;",
                    click: function () {
                        // var result = editor.get();
                        destroy();
                        if (okcallback !== undefined)
                            okcallback(result);
                        // hideBusyIndicator();
                    }
                }, {
                    text: "Cancel",
                    style: "color:#EE422E;",
                    click: function () {
                        destroy();
                        if (cancelcallback !== undefined)
                            cancelcallback();
                        // hideBusyIndicator();
                    }
                }]
            }).append('<img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRLqBq0ilAid0OE2A0Qx94ujF_M9DugbAGVyg&usqp=CAU" width = "100" height = "60"/>  ');
            $(".ui-dialog-titlebar-close").css('visibility', 'hidden');
            $("ui-dialog-titlebar").css('background', 'color: blue');
            $(".ui-dialog").css('border-style', 'solid');
            $(".ui-dialog").css('z-index', '505');
            $(".ui-dialog-titlebar").css('visibility', 'hidden');
            $(".ui-dialog-titlebar").css('background', 'color: red');
            $(".ui-dialog").css('modal', 'true');
            $(".ui-dialog").css('text-align', 'center');
            $(".ui-button").css('width', '100px');
            $(".ui-button").css('margin-top', '10px');
            $(".ui-button").css('margin-bottom', '10px');
            return true;
        }
 
    </script>
}

 

Views/Members/Delete.cshtml
@model W1.Models.Member

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Member</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LotNo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LotNo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AgentLastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AgentLastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AgentFirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AgentFirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.OfficePhone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.OfficePhone)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CellPhone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CellPhone)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AgentUrl)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AgentUrl)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ImageName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ImageName)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>


@section Scripts
            {
}

Views/Members/Index.cshtml
@model IEnumerable<W1.Models.Member>

@{
    ViewData["Title"] = "Index";
}

<h1 align="center">Homes Listed</h1>

<p align="center">
    <a asp-action="Create">Create New Listing</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.LotNo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AgentLastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AgentFirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.OfficePhone)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CellPhone)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AgentUrl)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ImageName)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.LotNo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AgentLastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AgentFirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.OfficePhone)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CellPhone)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AgentUrl)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ImageName)
            </td>
            <td>
              @*  <a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |   *@
                <a asp-action="Details" asp-route-id="@item.ID">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>
<br />
<br />
<div>
<i class="fa-solid fa-arrow-right"></i>
<a href="@Url.Action("Index", "Users")" style="color:blue;" class="menubar"
   data-toggle="tooltip" data-html="true" title="Placid Lot Owners">Placid Lot Owners</a>
</div>
@section Scripts
{
}